version: '3.4'

services:
  cmsdemoapi:
    image: cmsdemoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file:
    #   - .env
    ports:
      - 8000:8000
    volumes: 
      - ./:/app/
